Algoritmo "Maior ou menor que 10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo para dizer se um valor é maior ou menor que 10(dez)
// Autor(a)    : Guilherme Macedo
// Data atual  : 08/09/2024
Var
   num1: real
Inicio
      escreval("Digite um número: ")
      leia(num1)
      se num1 > 10 entao
      escreval("O número é maior que 10!")
      senao
      escreval("O número é menor que 10!")
      fimse
Fimalgoritmo