Algoritmo "Positivo ou negativo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo para verificar se o valor é postivo ou negativo.
// Autor(a)    : Guilherme Macedo
// Data atual  : 14/09/2024
Var
   numero: real
Inicio
   escreval ("Digite um valor para saber se é positivo ou negativo: ")
   leia(numero)
   se numero >= 0 entao
      escreval ("O número é positivo!")
   senao
      escreval ("O número é negativo!")
   fimse
Fimalgoritmo