Algoritmo "divisao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme
// Data atual  : 28/08/2024
Var
numero1: inteiro
numero2: inteiro
Resultado: real

Inicio
escreva ("Digite um número: ")
leia(numero1)
escreva ("Digite outro número: ")
leia(numero2)
Resultado <- numero1/numero2
escreva("O Resultado é: ", Resultado)

Fimalgoritmo