Algoritmo "SUCESSOR"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Atividade para mostrar o número de sucessor de outro número.
// Autor(a)    : Guilherme
// Data atual  : 28/08/2024
Var

   numero: inteiro
   sucessor: inteiro

Inicio

      escreval ("Digite um valor inteiro: ")
      leia(numero)
      sucessor <- numero + 1
      escreval ("O sucessor de ", numero, " é", sucessor)

Fimalgoritmo