Algoritmo "subtracao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Este algoritmo realiza a subtração de
//dois números fornecidos pelo usuário.
// Autor(a)    : Guilherme
// Data atual  : 28/08/2024
Var
numero1: inteiro
numero2: inteiro
Resultado: inteiro

Inicio
escreval ("Digite um número: ")
leia(numero1)
escreval ("Digite outro número: ")
leia(numero2)
resultado <- numero1 - numero2
escreva("O resultado é: ", Resultado)


Fimalgoritmo